version: '3.8'

services:
  db:
    image: postgres
    container_name: allan-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432/postgres
